name: Release Executables

on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check and Increase Tag Version
      id: check_and_increase_version
      run: |
        if git rev-parse --quiet --verify "refs/tags/v1.0"; then
          current_version=$(git describe --abbrev=0 --tags)
          IFS='.' read -r major minor patch <<< "$current_version"
          ((patch++))
          new_version="$major.$minor.$patch"
        else
          echo "Creating new tag v1.0"
          git tag -a v1.0 -m "Version 1.0"
          new_version="1.0.0"
        fi

    - name: Attach README.md to Tag
      run: |
        git tag -f -a v${{ env.new_version }} -F file_in_tag.txt
        git push origin v${{ env.new_version }}
