name: Release Executables

on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check and Increase Tag Version
      id: check_and_increase_version
      run: |
        if git rev-parse --quiet --verify "refs/tags/v1.0"; then
          current_version=$(git describe --abbrev=0 --tags)
          IFS='.' read -r major minor patch <<< "$current_version"
          ((patch++))
          new_version="$major.$minor.$patch"
          echo "Current version: $current_version"
          echo "New version will be: $new_version"
        else
          echo "Tag v1.0 does not exist. Creating new tag v1.0"
          git tag -a v1.0 -m "Version 1.0"
          new_version="1.0.0"
        fi
        echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Attach README.md to Tag
      run: |
        git tag -a v${{ env.new_version }} -m "Version ${{ env.new_version }}"
        git push origin v${{ env.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.new_version }}
        release_name: Release v${{ env.new_version }}
        body: |
          Release for version v${{ env.new_version }}
        draft: false
        files: file_in_tag.txt