name: Release Executables

on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Increment version
      id: increment_version
      uses: marvinpinto/github-tag-action@v7
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ steps.get_latest_tag.outputs.latest_tag }}
        tag_message: Release ${{ steps.get_latest_tag.outputs.latest_tag }}
        commit: ${{ github.sha }}

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.increment_version.outputs.new_tag }}
        release_name: Release ${{ steps.increment_version.outputs.new_tag }}
        draft: false
