name: Release Executables

on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check and Increase Tag Version
      id: check_and_increase_version
      run: |
        if git rev-parse --quiet --verify "refs/tags/v1.0"; then
          echo "::set-output name=exists::true"
          git describe --abbrev=0 --tags > current_version.txt
          current_version=$(cat current_version.txt)
          IFS='.' read -r major minor patch <<< "$current_version"
          ((patch++))
          new_version="$major.$minor.$patch"
          echo "::set-output name=new_version::$new_version"
        else
          echo "::set-output name=exists::false"
          echo "Creating new tag v1.0"
          git tag -a v1.0 -m "Version 1.0"
          echo "::set-output name=new_version::1.0"
        fi

    - name: Attach README.md to Tag
      run: |
        git archive --format=zip --output=README.zip HEAD:README.md
        git tag v${{ steps.increase_version.outputs.new_version }} -f -a -F README.zip